import 'package:flutter/material.dart';
import 'package:flutterapp/clone_20netflixapp/generatednetflixappscreen2widget/generated/GeneratedGroup2Widget1.dart';
import 'package:flutterapp/clone_20netflixapp/generatednetflixappscreen2widget/generated/GeneratedNavBarWidget.dart';
import 'package:flutterapp/clone_20netflixapp/generatednetflixappscreen2widget/generated/GeneratedButtonWidget.dart';
import 'package:flutterapp/clone_20netflixapp/generatednetflixappscreen2widget/generated/GeneratedCoverWidget.dart';
import 'package:flutterapp/clone_20netflixapp/generatednetflixappscreen2widget/generated/GeneratedUIBarsStatusBarsWhiteBaseWidget1.dart';
import 'package:flutterapp/clone_20netflixapp/generatednetflixappscreen2widget/generated/GeneratedGroupWidget8.dart';
import 'package:flutterapp/clone_20netflixapp/generatednetflixappscreen2widget/generated/GeneratedAlookatthepersonalandprofessionallivesofagroupofwomenwh.dart';
import 'package:flutterapp/clone_20netflixapp/generatednetflixappscreen2widget/generated/GeneratedEpisodeCardWidget.dart';
import 'package:flutterapp/clone_20netflixapp/generatednetflixappscreen2widget/generated/GeneratedBackgroundWidget2.dart';
import 'package:flutterapp/clone_20netflixapp/generatednetflixappscreen2widget/generated/GeneratedTabsWidget.dart';
import 'package:flutterapp/clone_20netflixapp/generatednetflixappscreen2widget/generated/GeneratedStarsWidget.dart';
import 'package:flutterapp/clone_20netflixapp/generatednetflixappscreen2widget/generated/GeneratedDescriptionWidget.dart';

/* Frame Netflix App / Screen #2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNetflixAppScreen2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 23, 20, 20),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedBackgroundWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 713.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 193.0,
                child: GeneratedEpisodeCardWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 612.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 33.0,
                child: GeneratedTabsWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 536.0,
                right: null,
                bottom: null,
                width: 224.0,
                height: 44.0,
                child: GeneratedStarsWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 408.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 106.0,
                child:
                    GeneratedAlookatthepersonalandprofessionallivesofagroupofwomenwh(),
              ),
              Positioned(
                left: 16.0,
                top: 332.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 44.0,
                child: GeneratedButtonWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 156.0,
                child: GeneratedCoverWidget(),
              ),
              Positioned(
                left: 144.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 44.0,
                child: GeneratedDescriptionWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 88.0,
                child: GeneratedNavBarWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedUIBarsStatusBarsWhiteBaseWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 669.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 20.0,
                child: GeneratedGroupWidget8(),
              ),
              Positioned(
                left: 145.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 201.0,
                height: 41.0,
                child: GeneratedGroup2Widget1(),
              )
            ]),
      ),
    ));
  }
}
